import { Link } from "wouter";
import Footer from "@/components/Footer";
import { ArrowLeft } from "lucide-react";
import { useStore } from "@/state/store";

export default function TermsOfService() {
  const isDark = useStore((state) => state.isDark);

  return (
    <div className={`min-h-screen ${isDark ? "dark bg-gray-950" : "bg-gray-50"} transition-colors duration-300 flex flex-col`}>
      <header className="fixed top-0 left-0 right-0 z-50 bg-white/80 dark:bg-gray-900/80 backdrop-blur-md border-b border-gray-200 dark:border-gray-800">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center">
          <Link href="/">
            <button className={`flex items-center gap-2 transition-colors ${isDark ? 'text-gray-300 hover:text-white' : 'text-gray-600 hover:text-gray-900'}`}>
              <ArrowLeft className="w-5 h-5" />
              <span className="font-medium">Back to Home</span>
            </button>
          </Link>
        </div>
      </header>

      <main className="flex-grow pt-24 pb-16">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="bg-white dark:bg-gray-900 rounded-2xl shadow-sm border border-gray-200 dark:border-gray-800 p-8 sm:p-12">
            <h1 className="text-3xl sm:text-4xl font-bold text-gray-900 dark:text-white mb-6">Terms of Service</h1>
            <div className="text-sm text-gray-500 dark:text-gray-400 mb-8">Last updated: {new Date().toLocaleDateString()}</div>
            
            <div className="prose prose-blue dark:prose-invert max-w-none space-y-6 text-gray-600 dark:text-gray-300">
              <p>
                Welcome to ArchStudio. By accessing or using our website, AI design tools, and services, you agree to be bound by these Terms of Service. Please read them carefully.
              </p>

              <h2 className="text-xl font-semibold text-gray-900 dark:text-white mt-8 mb-4">1. Acceptance of Terms</h2>
              <p>
                By accessing and using ArchStudio ("we," "us," or "our"), you accept and agree to be bound by the terms and provision of this agreement. In addition, when using these particular services, you shall be subject to any posted guidelines or rules applicable to such services.
              </p>

              <h2 className="text-xl font-semibold text-gray-900 dark:text-white mt-8 mb-4">2. Description of Service</h2>
              <p>
                ArchStudio provides users with access to a collection of AI-powered architectural design tools, including but not limited to 2D floor plan generation, 3D modeling, and design export tools (the "Service"). You understand and agree that the Service is provided "AS-IS" and that we assume no responsibility for the timeliness, deletion, mis-delivery, or failure to store any user communications or personalization settings.
              </p>

              <h2 className="text-xl font-semibold text-gray-900 dark:text-white mt-8 mb-4">3. AI Generation and Accuracy Disclaimer</h2>
              <p>
                The designs, floor plans, and 3D models generated by ArchStudio are created using artificial intelligence algorithms. You acknowledge that:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Generated designs are for conceptual and visualization purposes only.</li>
                <li>We do not guarantee the structural integrity, safety, or compliance with local building codes of any generated design.</li>
                <li>All designs should be reviewed and approved by a licensed architect, structural engineer, or contractor before being used for actual construction.</li>
                <li>ArchStudio shall not be liable for any damages resulting from the use of generated designs in real-world applications.</li>
              </ul>

              <h2 className="text-xl font-semibold text-gray-900 dark:text-white mt-8 mb-4">4. Intellectual Property Rights</h2>
              <p>
                You retain all rights, title, and interest in and to any specific requirements, parameters, or base floor plans you submit to the Service. ArchStudio grants you a non-exclusive, worldwide, royalty-free license to use, reproduce, modify, and display the final designs and models generated by the Service based on your inputs.
              </p>

              <h2 className="text-xl font-semibold text-gray-900 dark:text-white mt-8 mb-4">5. Limitation of Liability</h2>
              <p>
                In no event shall ArchStudio, its officers, directors, employees, or agents, be liable to you for any direct, indirect, incidental, special, punitive, or consequential damages whatsoever resulting from any errors, mistakes, or inaccuracies of content, personal injury or property damage, of any nature whatsoever, resulting from your access to and use of our Service.
              </p>

              <h2 className="text-xl font-semibold text-gray-900 dark:text-white mt-8 mb-4">6. Modifications to Service</h2>
              <p>
                We reserve the right at any time and from time to time to modify or discontinue, temporarily or permanently, the Service (or any part thereof) with or without notice. You agree that ArchStudio shall not be liable to you or to any third party for any modification, suspension or discontinuance of the Service.
              </p>
            </div>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
