import { jsPDF } from "jspdf";
import html2canvas from "html2canvas";

export const exportToPDF = async (layoutData: any) => {
  // Create new PDF document
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4"
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - 2 * margin;

  let yPos = margin;

  // Header & Title
  doc.setFillColor(31, 41, 55); // Dark gray
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("Design Studio", margin, 20);
  
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text("Architecture Layout Report", margin, 30);
  
  yPos = 50;
  doc.setTextColor(31, 41, 55);

  // Summary Info
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Project Summary", margin, yPos);
  yPos += 10;

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(`Total Rooms: ${layoutData?.length || 0}`, margin, yPos);
  yPos += 8;

  let totalArea = 0;
  layoutData?.forEach((room: any) => {
    totalArea += room.width * room.depth;
  });
  doc.text(`Total Area: ${totalArea.toFixed(2)} sq units`, margin, yPos);
  yPos += 15;

  // Room Details Table
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Room-by-Room Breakdown", margin, yPos);
  yPos += 10;

  const tableHeaders = ["Room", "Dimensions (W x D x H)", "Area (sq m)"];
  const colWidths = [40, 90, 40];
  let headerX = margin;

  // Draw table header
  doc.setFillColor(243, 244, 246); // Light gray bg
  doc.rect(margin, yPos - 6, contentWidth, 10, 'F');
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  tableHeaders.forEach((header, idx) => {
    doc.text(header, headerX, yPos);
    headerX += colWidths[idx];
  });
  yPos += 10;

  // Draw table rows
  doc.setFont("helvetica", "normal");
  layoutData?.forEach((room: any, index: number) => {
    const area = (room.width * room.depth).toFixed(2);
    const dimensions = `${room.width.toFixed(1)}m × ${room.depth.toFixed(1)}m × ${room.height.toFixed(1)}m`;
    
    let rowX = margin;
    
    // Alternating row background
    if (index % 2 === 1) {
      doc.setFillColor(249, 250, 251);
      doc.rect(margin, yPos - 6, contentWidth, 10, 'F');
    }

    doc.text(`Room ${index + 1}`, rowX, yPos);
    rowX += colWidths[0];
    doc.text(dimensions, rowX, yPos);
    rowX += colWidths[1];
    doc.text(`${area} sq m`, rowX, yPos);

    yPos += 10;

    if (yPos > pageHeight - margin - 30) {
      doc.addPage();
      yPos = margin + 10;
    }
  });

  yPos += 10;

  try {
    // Capture 2D floor plan
    const floorPlanElement = document.querySelector("[data-testid='canvas-floor-plan']")?.parentElement;
    if (floorPlanElement) {
      if (yPos > pageHeight - margin - 100) {
        doc.addPage();
        yPos = margin + 10;
      }

      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("2D Floor Plan", margin, yPos);
      yPos += 10;

      const canvas2d = await html2canvas(floorPlanElement, { 
        backgroundColor: '#111827', // Match dark theme roughly
        scale: 2
      });
      const imgData = canvas2d.toDataURL("image/png");
      
      const imgWidth = contentWidth;
      const imgHeight = (canvas2d.height / canvas2d.width) * imgWidth;

      // Draw border
      doc.setDrawColor(200, 200, 200);
      doc.rect(margin, yPos, imgWidth, imgHeight);
      doc.addImage(imgData, "PNG", margin, yPos, imgWidth, imgHeight);
      yPos += imgHeight + 20;
    }

    // Capture 3D model
    const threeDCanvas = document.querySelector("canvas:not([data-testid='canvas-floor-plan'])") as HTMLCanvasElement;
    if (threeDCanvas) {
      if (yPos > pageHeight - margin - 100) {
        doc.addPage();
        yPos = margin + 10;
      }

      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("3D Perspective View", margin, yPos);
      yPos += 10;

      const imgData = threeDCanvas.toDataURL("image/png");
      const imgWidth = contentWidth;
      const imgHeight = (threeDCanvas.height / threeDCanvas.width) * imgWidth;

      if (yPos + imgHeight > pageHeight - margin - 10) {
        doc.addPage();
        yPos = margin + 10;
      }

      doc.setDrawColor(200, 200, 200);
      doc.rect(margin, yPos, imgWidth, imgHeight);
      doc.addImage(imgData, "PNG", margin, yPos, imgWidth, imgHeight);
    }
  } catch (error) {
    console.error("Error generating screenshots for PDF", error);
  }

  // Footer on all pages
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by Design Studio on ${new Date().toLocaleString()}`,
      margin,
      pageHeight - 10
    );
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth - margin - 20,
      pageHeight - 10
    );
  }

  // Save PDF
  doc.save("architecture-layout-report.pdf");
};

export const exportToImage = () => {
  const canvas = document.querySelector("canvas:not([data-testid='canvas-floor-plan'])") as HTMLCanvasElement;
  if (canvas) {
    const dataURL = canvas.toDataURL("image/png");
    const link = document.createElement("a");
    link.download = "3d-layout-preview.png";
    link.href = dataURL;
    link.click();
  } else {
    alert("3D view not available for export");
  }
};
