import { jsPDF } from "jspdf";
import html2canvas from "html2canvas";

export const exportToPDF = async (layoutData: any) => {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - 2 * margin;
  let yPos = margin;

  doc.setFillColor(31, 41, 55);
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("Design Studio", margin, 20);
  
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text("Architecture Layout Report", margin, 30);
  
  yPos = 50;
  doc.setTextColor(31, 41, 55);

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Project Summary", margin, yPos);
  yPos += 10;

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(`Total Rooms: ${layoutData?.length || 0}`, margin, yPos);
  yPos += 8;

  let totalArea = 0;
  layoutData?.forEach((room: any) => {
    totalArea += room.width * room.depth;
  });
  doc.text(`Total Area: ${totalArea.toFixed(2)} sq units`, margin, yPos);
  yPos += 15;

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Room-by-Room Breakdown", margin, yPos);
  yPos += 10;

  const tableHeaders = ["Room", "Dimensions (W x D x H)", "Area (sq m)"];
  const colWidths = [40, 90, 40];
  let headerX = margin;

  doc.setFillColor(243, 244, 246);
  doc.rect(margin, yPos - 6, contentWidth, 10, 'F');
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  tableHeaders.forEach((header, idx) => {
    doc.text(header, headerX, yPos);
    headerX += colWidths[idx];
  });
  yPos += 10;

  doc.setFont("helvetica", "normal");
  layoutData?.forEach((room: any, index: number) => {
    const area = (room.width * room.depth).toFixed(2);
    const dimensions = `${room.width.toFixed(1)}m × ${room.depth.toFixed(1)}m × ${room.height.toFixed(1)}m`;
    
    let rowX = margin;
    if (index % 2 === 1) {
      doc.setFillColor(249, 250, 251);
      doc.rect(margin, yPos - 6, contentWidth, 10, 'F');
    }

    doc.text(room.name || `Room ${index + 1}`, rowX, yPos);
    rowX += colWidths[0];
    doc.text(dimensions, rowX, yPos);
    rowX += colWidths[1];
    doc.text(`${area} sq m`, rowX, yPos);

    yPos += 10;
    if (yPos > pageHeight - margin - 30) {
      doc.addPage();
      yPos = margin + 10;
    }
  });

  yPos += 10;

  try {
    const floorPlanElement = document.querySelector(".touch-none")?.parentElement;
    if (floorPlanElement) {
      if (yPos > pageHeight - margin - 100) { doc.addPage(); yPos = margin + 10; }

      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("2D Floor Plan", margin, yPos);
      yPos += 10;

      const canvas2d = await html2canvas(floorPlanElement, { 
        backgroundColor: '#111827', scale: 2
      });
      const imgData = canvas2d.toDataURL("image/png");
      const imgWidth = contentWidth;
      const imgHeight = (canvas2d.height / canvas2d.width) * imgWidth;

      doc.setDrawColor(200, 200, 200);
      doc.rect(margin, yPos, imgWidth, imgHeight);
      doc.addImage(imgData, "PNG", margin, yPos, imgWidth, imgHeight);
      yPos += imgHeight + 20;
    }

    const threeDCanvas = document.querySelector("canvas") as HTMLCanvasElement;
    if (threeDCanvas) {
      if (yPos > pageHeight - margin - 100) { doc.addPage(); yPos = margin + 10; }

      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("3D Perspective View", margin, yPos);
      yPos += 10;

      const imgData = threeDCanvas.toDataURL("image/png");
      const imgWidth = contentWidth;
      const imgHeight = (threeDCanvas.height / threeDCanvas.width) * imgWidth;

      if (yPos + imgHeight > pageHeight - margin - 10) { doc.addPage(); yPos = margin + 10; }

      doc.setDrawColor(200, 200, 200);
      doc.rect(margin, yPos, imgWidth, imgHeight);
      doc.addImage(imgData, "PNG", margin, yPos, imgWidth, imgHeight);
    }
  } catch (error) {
    console.error("Error generating screenshots for PDF", error);
  }

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Generated by Design Studio on ${new Date().toLocaleString()}`, margin, pageHeight - 10);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin - 20, pageHeight - 10);
  }

  doc.save("architecture-layout-report.pdf");
};

export const exportToImage = () => {
  const canvas = document.querySelector("canvas") as HTMLCanvasElement;
  if (canvas) {
    const dataURL = canvas.toDataURL("image/png");
    const link = document.createElement("a");
    link.download = "3d-layout-preview.png";
    link.href = dataURL;
    link.click();
  } else {
    alert("3D view not available for export");
  }
};

export const exportToJSON = (data: any) => {
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.download = "layout-project.json";
  link.href = url;
  link.click();
};

export const exportToDXF = (floors: any[]) => {
  let dxf = `0\nSECTION\n2\nENTITIES\n`;
  
  floors.forEach(floor => {
    floor.rooms.forEach((room: any) => {
      const w = room.width / 2;
      const d = room.depth / 2;
      const x = room.position[0];
      const y = room.position[2]; // Z is Y in 2D
      
      const pts = [
        [x - w, y - d],
        [x + w, y - d],
        [x + w, y + d],
        [x - w, y + d]
      ];

      // Draw 4 lines for each room
      for(let i=0; i<4; i++) {
        const p1 = pts[i];
        const p2 = pts[(i+1)%4];
        dxf += `0\nLINE\n8\n${floor.name.replace(/\s+/g, '_')}\n10\n${p1[0]}\n20\n${p1[1]}\n30\n0.0\n11\n${p2[0]}\n21\n${p2[1]}\n31\n0.0\n`;
      }
    });
  });
  
  dxf += `0\nENDSEC\n0\nEOF\n`;
  const blob = new Blob([dxf], { type: "application/dxf" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.download = "layout-project.dxf";
  link.href = url;
  link.click();
};
